version: '3'
services:
  web_t4:
    image: java_springv1
    build: .
    ports:
      - "8094:8085"
    volumes:
      - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/t4_csateam/volumes
