version: '3'
services:
  web_t4:
    platform: linux/x86_64
    image: java_springv1_t4
    build: .
    ports:
      - "8094:8085"
    volumes:
      - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/pi/apps/CSATeam/volumes
